vim.cmd("colorscheme zephyr")

require("set")
require("plugins")
require("treesitter-config")
require("fugitive")
require("undotree")
require("nvim-tree-config")
require("leap-config")
require("lualine-config")
require("git-blame-config")
require("neoscroll-config")
require("neoformat-config")
require("lsp")
require("comment-config")
